version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  geth:
    image: ethereum/client-go:${GETH_DOCKER_TAG}
    env_file: .env
    restart: unless-stopped
    command: 
      - geth
      - --goerli
      - --http
      - --http.addr=0.0.0.0 
      - --http.vhosts="*"
      - --http.api="db,eth,net,web3,personal"
      - --authrpc.jwtsecret=/root/jwtsecret
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
    stop_grace_period: 5m
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8551:8551
    volumes:
      - ./data/geth:/root/.ethereum
      - ./config/jwtsecret:/root/jwtsecret
    networks:
      - n_bridge
    <<: *logging

  prysm_beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_DOCKER_TAG}
    restart: unless-stopped
    command:
      - --prater
      - --datadir=/data
      - --jwt-secret=/jwtsecret
      - --checkpoint-sync-url=https://goerli.beaconstate.info
      - --genesis-beacon-api-url=https://goerli.beaconstate.info
      - --execution-endpoint=http://geth:8551
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --monitoring-host=0.0.0.0
      - --p2p-tcp-port=13000
      - --p2p-max-peers=100
      - --accept-terms-of-use
    volumes:
      - ./data/prysm/beacon:/data
      - ./data/prysm/genesis:/genesis
      - ./config/jwtsecret:/jwtsecret
    ports:
      - 4000:4000
      - 3500:3500
      - 8900:8080
      - 13000/tcp
      - 12000/udp
    networks:
      - n_vouch_beacons
      - n_slasher_beacon
      - n_bridge
    <<: *logging

  prysm_validator:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    restart: unless-stopped
    user: "0"
    command:
      - --prater
      - --datadir=/data
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
      - --monitoring-host=0.0.0.0
      - --beacon-rpc-provider=prysm_beacon:4000
      - --wallet-dir=/data/wallets
      - --wallet-password-file=/data/passphrases
    volumes:
      - ./data/prysm/beacon-slasher:/data
      - ./data/prysm/genesis:/genesis
      - ./config/jwtsecret:/jwtsecret
      - ./wallets:/data/wallets:ro
      - ./config/dirk/passphrases:/data/passphrases:ro
    depends_on:
      - prysm_beacon
    networks:
      - n_slasher_beacon
    <<: *logging

  prysm_slasher:
    image: gcr.io/prysmaticlabs/prysm/slasher:latest
    restart: unless-stopped
    command:
      - --prater
      - --datadir=/data
      - --monitoring-host=0.0.0.0
      - --beacon-rpc-provider=prysm_beacon:4000
    volumes:
      - ./data/prysm/beacon-slasher:/data
      - ./data/prysm/genesis:/genesis
      - ./config/jwtsecret:/jwtsecret
    depends_on:
      - prysm_beacon
    networks:
      - n_slasher_beacon
    <<: *logging

  lighthouse_beacon:
    image: sigp/lighthouse:${LIGHTHOUSE_DOCKER_TAG}
    restart: unless-stopped
    env_file: .env
    command:
      - lighthouse 
      - beacon_node
      - --network=goerli
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
      - --execution-jwt=/root/jwtsecret
      - --http 
      - --http-address=0.0.0.0
      - --checkpoint-sync-url=https://goerli.beaconstate.info
      - --execution-endpoint=http://geth:8551
    volumes:
      - ./data/sigmaprime/lighthouse:/root/.lighthouse
      - ./config/jwtsecret:/root/jwtsecret
    depends_on:
      - geth
    ports:
      - 5052:5052/tcp
      - 8910:5054
      - 9000:9000/tcp
      - 9000:9000/udp
    networks:
      - n_vouch_beacons
      - n_bridge
    <<: *logging

  nimbus_beacon:
    image: statusim/nimbus-eth2:${NIMBUS_DOCKER_TAG}
    user: "0"
    restart: unless-stopped
    command:
      - --network=goerli
      - --data-dir=/opt/app/beacon
      - --validators-dir=/opt/app/validators
      - --secrets-dir=/opt/app/secrets
      - --web3-url=http://geth:8551
      - --tcp-port=9001
      - --udp-port=9001
      - --rpc
      - --rpc-port=9190
      - --metrics
      - --metrics-port=8008
      - --metrics-address=0.0.0.0
      - --rest
      - --rest-address=0.0.0.0
      - --suggested-fee-recipient=${SUGGESTED_FEE_RECIPIENT}
    ports:
      - 9190:9190 # rpc
      - 9001:9001/tcp
      - 9001:9001/udp
    volumes:
      - ./data/nimbus/beacon:/opt/app/beacon
      - ./data/nimbus/validator/validators:/opt/app/validators
      - ./data/nimbus/validator/secrets:/opt/app/secrets
    networks:
      - n_vouch_beacons
      - n_bridge
    <<: *logging

  vouch:
    image: attestant/vouch:${VOUCH_DOCKER_TAG}
    restart: unless-stopped
    command: ["--base-dir=/config"]
    volumes:
      - ./config/vouch/vouch.yml:/config/vouch.yml:ro
      - ./config/vouch/certs:/config/certs:ro
    networks:
      - n_dirk_vouch
      - n_vouch_beacons
    <<: *logging
  
  dirk:
    image: attestant/dirk:${DIRK_DOCKER_TAG}
    restart: unless-stopped
    command: ["--base-dir=/config"]
    volumes:
      - ./config/dirk/dirk.yml:/config/dirk.yml:ro
      - ./config/dirk/certs:/config/certs:ro
      - ./wallets:/wallets:ro
      - ./config/dirk/passphrases:/config/passphrases:ro
      - ./data/attestant/dirk:/data
    networks:
      - n_dirk_vouch
    <<: *logging

  mevboost:
    image: flashbots/mev-boost:${MEVBOOST_DOCKER_TAG}
    restart: unless-stopped
    command:
      - -addr=0.0.0.0:18550
      - -goerli
      - -relay-check
      - -relays=https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net
      - -min-bid=0.02
    networks:
      - n_grafana_prometheus
      - n_vouch_beacons
    <<: *logging

  prometheus:
    image: prom/prometheus:${PROMETHEUS_DOCKER_TAG}
    user: root
    restart: unless-stopped
    hostname: prometheus
    command: --storage.tsdb.retention.time=7d --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
    networks:
      - n_grafana_prometheus
      - n_dirk_vouch
      - n_vouch_beacons
    <<: *logging

  grafana:
    image: grafana/grafana:${GRAFANA_DOCKER_TAG}
    restart: unless-stopped
    hostname: grafana
    user: "0"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8082/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000    
    networks:
      - n_grafana_prometheus
      - n_bridge
    <<: *logging

  renderer:
    image: grafana/grafana-image-renderer:${GRAFANA_IMAGE_RENDERER_TAG}
    user: "0"
    restart: on-failure
    hostname: renderer
    environment:
      ENABLE_METRICS: 'true'
      HTTP_PORT: 8082
    networks:
      - n_grafana_prometheus
    <<: *logging

  node-exporter:
    image: prom/node-exporter:${PROMETHEUS_NODE_EXPORTER_DOCKER_TAG}
    user: "0"
    hostname: node-exporter
    networks:
      - n_grafana_prometheus
    <<: *logging  

networks:
  # bridge network - this networks gets internet access!
  n_bridge:
    
  # vouch to beacons
  n_vouch_beacons:
    internal: true

  # slasher to beacon:
  n_slasher_beacon:
    internal: true

  # dirk to vouch
  n_dirk_vouch:
    internal: true
  
  # grafana to prometheus
  n_grafana_prometheus:
    internal: true

# EOF
