version: "3.7"

x-limit-node:
  &limit-node
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "10G"

x-limit-miniservice:
  &limit-miniservice
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"

services:
  geth:
    <<: *limit-node
  # prysm:
  #   <<: *limit-node
  lighthouse:
    <<: *limit-node
  nimbus:
    <<: *limit-node
  vouch:
    <<: *limit-miniservice
  dirk:
    <<: *limit-miniservice
  prometheus:
    <<: *limit-miniservice
  grafana:
    <<: *limit-miniservice

# EOF
